/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as coinFlipSol from "./CoinFlip.sol";
export * as delegationSol from "./Delegation.sol";
export * as telephoneSol from "./Telephone.sol";
export * as tokenSol from "./Token.sol";
