/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITelephone__factory } from "./ITelephone__factory";
export { Telephone__factory } from "./Telephone__factory";
