/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as coinFlipSol from "./CoinFlip.sol";
export type { coinFlipSol };
import type * as telephoneSol from "./Telephone.sol";
export type { telephoneSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export * as factories from "./factories";
export type { CoinFlip } from "./CoinFlip.sol/CoinFlip";
export { CoinFlip__factory } from "./factories/CoinFlip.sol/CoinFlip__factory";
export type { ICoinFlip } from "./CoinFlip.sol/ICoinFlip";
export { ICoinFlip__factory } from "./factories/CoinFlip.sol/ICoinFlip__factory";
export type { ITelephone } from "./Telephone.sol/ITelephone";
export { ITelephone__factory } from "./factories/Telephone.sol/ITelephone__factory";
export type { Telephone } from "./Telephone.sol/Telephone";
export { Telephone__factory } from "./factories/Telephone.sol/Telephone__factory";
export type { IToken } from "./Token.sol/IToken";
export { IToken__factory } from "./factories/Token.sol/IToken__factory";
export type { Token } from "./Token.sol/Token";
export { Token__factory } from "./factories/Token.sol/Token__factory";
